### ISSUE TITLE
Unlock features with schema in DSE and FE

### ISSUE THREAD

**Issue by domire8** [aica-technology/api#87]
We should continue to explore the possibilities of using our application schema throughout the stack to validate YAML syntax. As it was mentioned in [this comment](https://github.com/aica-technology/api/issues/62#issuecomment-1775575486), there are a lot of features to try.

```[tasklist]
### Tasks
- [ ] https://github.com/aica-technology/backend/issues/121
- [ ] https://github.com/aica-technology/dynamic-state-engine/issues/204
- [ ] https://github.com/aica-technology/frontend/issues/533
- [ ] Associate content with the syntax version when storing apps in a database
```

**Comment by eeberhard** [comment]
Thanks, I think that last point is really something bigger which would constitute a separate epic. I'll write the subtasks here for now but then flesh them out in an epic at a future point:

- (backend-api) Add schema version to the application database resource argparser when adding apps
- (frontend) Set the current schema version when writing apps to the database
- (frontend) Check the schema version against the current version when loading applications from the database
  - (this is the hard one) what to do if the schema version is out of date? Ideally open a dialogue with the user with a migration guide specific to each version change, and let them re-save the application with updated syntax.
